name: build_and_test

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        - name: win64-vstudio-debug
          run:  python3 fips build win64-vstudio-debug
        - name: win64-vstudio-release
          run:  python3 fips build win64-vstudio-release
        - name: madNES win64-vstudio-debug
          run:  python3 fips run madNES win64-vstudio-debug
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v4
        - name: osx-make-debug
          run:  python3 fips build osx-make-debug
        - name: osx-make-release
          run:  python3 fips build osx-make-release
        - name: madNES osx-make-debug
          run:  python3 fips run madNES osx-make-debug
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: prepare
          run:  |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
        - name: linux-make-debug
          run:  python3 fips build linux-make-debug
        - name: linux-make-release
          run:  python3 fips build linux-make-release
        - name: madNES linux-make-debug
          run:  python3 fips run madNES linux-make-debug
    emscripten:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: install emsdk
          run: |
            sudo apt-get install ninja-build
            python3 fips emsdk install latest
        - name: wasm-ninja-debug
          run:  python3 fips build wasm-ninja-debug
        - name: wasm-ninja-release
          run:  python3 fips build wasm-ninja-release
